#!/bin/bash

mod=
impl=

get_args() {
  while [[ $# -gt 0 ]]; do
    arg=$1
    shift

    case $arg in
      -e) impl=ex ;;
      -r) impl=rust ;;
      one_max) mod=one_max ;;
      onemax) mod=one_max ;;
      *)
        echo "Invalid arg: $arg"
        exit 0
        ;;
    esac
  done
}

get_args $@

if [[ -z $mod || -z $impl ]]; then
  echo "Missing arg"
  echo "module: $mod"
  echo "impl: $impl"
  exit 0
fi

echo "Running $mod $impl ..."

MIX_ENV=prod mix run "lib/main.exs" "$mod" "$impl"
